Feat: implementing colored output to the terminal

diff --git a/hunter b/hunter
--- a/hunter
+++ b/hunter
@@ -5,6 +5,12 @@ base_folder=$(pwd)
 cmd=$1
 sub_cmd=$2
 
+# Colors
+red='\033[0;31m'
+green='\033[0;32m'
+blue='\033[0;34m'
+clear='\033[0m'
+
 write_module(){
 
 if [[ -z ${1+x} ]]; then
@@ -57,7 +63,7 @@ fi
 
 if [[ $1 == 'header' ]]; then
 	if [[ -f $dest_folder/$module_file_name ]]; then
-	echo "-- Hunter C --"
+	echo -e "${blue}>>--Hunter C-->${clear}"
 	echo "CALLED FROM: $0"
 	echo "ERROR: Header file $module_file_name already exists in /headers"
 	exit 1
@@ -81,8 +87,8 @@ if [[ $cmd == 'create' ]]; then
 		check_dest_folder $sub_cmd
 		check_module_existence $sub_cmd
 		write_module $sub_cmd
-
-	echo "Header $module_file_name was successfully created!
+	echo -e "${blue}>>--Hunter C-->${clear}"	
+	echo -e "Header $module_file_name was ${green}successfully created!${clear}
 Run 'cat headers/$module_file_name' to inspect it."
 	elif [[ $sub_cmd == 'impl' ]]; then 
 		module_name=$3
@@ -91,17 +97,18 @@ Run 'cat headers/$module_file_name' to inspect it."
 		check_dest_folder $sub_cmd
 		check_module_existence $sub_cmd
 		write_module $sub_cmd
-		
+	
 	echo "Implementation file $module_file_name was successfully created!
 Run 'cat src/$module_file_name' to inspect it."
 	else
-		echo "-- Hunter C --"
+		echo -e "${blue}>>--Hunter C-->${clear}"
 		echo "CALLED FROM: $0"
 		echo "ERROR: hunter $cmd $sub_cmd is not a valid command. Hit hunter help for more info"
 		exit 1 
 	fi
 else
-	echo "-- Hunter C --"
+	echo -e "${blue}>>--Hunter C-->${clear}"
 	echo "CALLED FROM: $0"
-	echo "ERROR: 'hunter $cmd' is not a recognized command. Hit hunter help to more info"
+	echo -e "ERROR: 'hunter $cmd' ${red}is not a recognized command${clear}. Hit hunter help to more info"
+	exit 1
 fi 
